version: "3"

services:
  server:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./cert/:/cert/
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    restart: always

networks:
  nginx:
    external: true